/*@@ Generated by Wedit @@ */
#include <windows.h>
#include <lfc.h>
#include "my_icqres.h"

/*@@Callbacks Section--------------------------------------Callbacks Section@@*/
/*@@Dialog "Dlg100"------------------------------------------Dialog "Dlg100"@@*/
static ST_DIALOGBOX *Set_Dlg100_Fields(HWND hwnd)
{
	struct _Dlg100 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg100));
	s->id_text = GetControl(std,104);
	s->id_config = GetControl(std,105);
	s->id_status = GetControl(std,103);
	s->id_screen = GetControl(std,102);
	s->idok = GetControl(std,1);
	s->idcancel = GetControl(std,2);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg100(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	ST_DIALOGBOX *std;
	struct _Dlg100 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			std = ST_InitDialogBox(hwnd);
			Set_Dlg100_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg100Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case ID_TEXT:
				break;
				case ID_SCREEN:
				switch(HIWORD(wParam)) {
					case EN_KILLFOCUS:
						Dlg100Edit_field102KillFocus(GetControl(std,102),s);
						break;
				}
				break;
				case IDOK:
					{
						int r;
						
						/* if the user procedure returns a value != 0 end the dialog */
						r = Dlg100OkSelected(GetControl(std,IDCANCEL),s);
						if (r) {
							EndDialog(hwnd,r);
						}
						return(TRUE);
					}
				case IDCANCEL:
					Dlg100CancelSelected(GetControl(std,2),s);
				break;
			}
			break;
		case WM_DESTROY:
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg100(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(100),parent,Dlg100);
}
HWND StartDlg100(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(100),parent,Dlg100);
}
/*@@Dialog "Dlg500"------------------------------------------Dialog "Dlg500"@@*/
static ST_DIALOGBOX *Set_Dlg500_Fields(HWND hwnd)
{
	struct _Dlg500 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg500));
	s->id_exit = GetControl(std,505);
	s->id_reset = GetControl(std,504);
	s->id_save = GetControl(std,503);
	s->id_names = GetControl(std,501);
	s->id_values = GetControl(std,502);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg500(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	static HFONT DialogFont;
	ST_DIALOGBOX *std;
	struct _Dlg500 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			DialogFont = SetDialogFont(hwnd,"MS Sans Serif",8,400);
			CenterWindow(hwnd,1);
			std = ST_InitDialogBox(hwnd);
			Set_Dlg500_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg500Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case ID_EXIT:
					Dlg500Push_button505Selected(GetControl(std,505),s);
				break;
				case ID_RESET:
					Dlg500Push_button504Selected(GetControl(std,504),s);
				break;
				case ID_SAVE:
					Dlg500Push_button503Selected(GetControl(std,503),s);
				break;
				case ID_NAMES:
				break;
				case ID_VALUES:
				break;
			}
			break;
		case WM_DESTROY:
			DeleteObject(DialogFont);
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg500(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(500),parent,Dlg500);
}
HWND StartDlg500(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(500),parent,Dlg500);
}
